### ISSUE TITLE
Application Filtering

### ISSUE THREAD

**Issue by eddyv** [ssh24/eecs-gradapps#17]
# TODO
 - [x] Live client side "selected filter"
 - [x] Notification for when a result returns no tables
 - [x] Order by (columns)
 - [x] Fix set to operations to load the same table columns as the filter
 - [x] Highlight/bold filter in table
 - [ ] check for faculty member .htpasswd before server side .htpasswd
 - [ ] Presets
 - [ ] Create an application dashboard page for each application (to be redirected upon clicking `View Application`)
