### ISSUE TITLE
Admin View

### ISSUE THREAD

**Issue by ssh24** [ssh24/eecs-gradapps#26]
# Description

Admin view deliverables according to the [requirements document](https://github.com/ssh24/EECS4090-Project/blob/master/doc/rdoc/Latex/grad-apps-rdoc.pdf).

# Acceptance Criteria

- [x] An admin shall be able to upload a student application to the portal
- [x] An admin shall be able to update all attributes of a student application
- [x] An admin shall be able to export the applications to CSV format
- [x] An admin shall be able to see details about an application in an
organized table
- [x] An admin shall be able to filter student applications
- [x] An admin shall be able to save filter presets
- [x] An admin shall be able to add a new member to the list of EECS graduate
program members
- [x] An admin shall be able to remove a member from the list of EECS graduate
program members except for themselves
- [x] An admin shall be able to assign/remove roles from an existing faculty member
- [x] Add user settings functionality
- [x] An admin shall be able to assign applications to be reviewed by committee members
- [x] An admin shall be able to unassign applications to be reviewed by committee members (only if they are still in `New` stage of the review)
- [x] An admin shall be able to dismiss applications to be reviewed by committee members (only if they are still in `Submitted` stage of the review)
- [x] Add unit tests
- [x] Add user manual docs
- [x] Append it as a link in the footer to open as pdf
