### ISSUE TITLE
Professor View

### ISSUE THREAD

**Issue by ssh24** [ssh24/eecs-gradapps#27]
# Description

Professor view deliverables according to the [requirements document](https://github.com/ssh24/EECS4090-Project/blob/master/doc/rdoc/Latex/grad-apps-rdoc.pdf).

# Acceptance Criteria

- [x] A professor shall be able to set status of an application to:
  - [x] Contacted
  - [x] Not Contacted
  - [x] Requested
  - [x] Not Requested
  - [x] Interested
  - [x] Not Interested
- [x] A professor shall be able to filter applications as specified in the requirements document to narrow down student applicants
-  [x] A professor shall be able to order applicants in either ascending or descending order on their choice of fields (multi-attribute fields such as fields of interest are not supported for ordering)
- [x] A professor can save their favorite filter as a preset to be able to reuse it without building it every time
- [x] A professor shall be able to view the application overview as an outlined html page
- [x] Add user manual docs
- [x] Add unit tests on all features
