### ISSUE TITLE
Committee Member View

### ISSUE THREAD

**Issue by ssh24** [ssh24/eecs-gradapps#28]
# Description

Committee member view deliverables according to the [requirements document](https://github.com/ssh24/EECS4090-Project/blob/master/doc/rdoc/Latex/grad-apps-rdoc.pdf).

# Acceptance Criteria

- [x] A committee member shall be able to see the list of new and previously reviewed
application(s)
- [x] A committee member shall be able to apply filtering to reviews
- [x] A committee member shall be able to save filter presets
- [x] A committee member shall be able to save applications as a draft for future completion
- [x] A committee member shall be able use or add a university assessment
if it has already been used when reviewing applications
- [x] Add user manual docs
